### ISSUE TITLE
 When form validations fail, Add nested button behaviour is not woking.

### ISSUE THREAD

**Issue by tirnavali** [arielj/vanilla-nested#47] opened 2022-02-22 19:38 UTC
I think this problem is related with turbo but i can not solve it.

https://user-images.githubusercontent.com/58842032/155206151-04b216b3-0205-486c-a7c8-837043f19b43.mov

**Comment by arielj** [comment] 2022-03-28 19:54
can you share a test app to reproduce this? the code listens to the `turbo:load` event, maybe this is fireing a different event?

I think I have to move the event listener to the `document` element instead of querying all the elements, that way it should work for any element that is added after too, an app to reproduce this would be realyl useful because I did some tests with turbo but I can't seem to reproduce this exact case

**Comment by arielj** [comment] 2022-03-28 20:50
hey @tirnavali can you try using the gem from the github repo instead of rubygems/yarn? https://github.com/arielj/vanilla-nested#installation (check the alternate code using `arielj/vanilla-nested` as the source if you are using both the rails gem and the yarn package)

I pushed a refactor that should fix your problem, I would like to get some confirmation if it worked for you before making a release

**Comment by alviandf** [comment] 2022-04-18 06:11
yeah I have that issue too

**Comment by arielj** [comment] 2022-04-18 12:40
@alviandf can you try with the latest commit from github instead of the version uploaded to rubygems and npm? I think it should be fixed with my latest changes, I would like to have confirmation before making a release

check the installation section in the readme on how to use github for both yarn and bundler

**Comment by snjhyrglr** [comment] 2022-06-10 06:49
@arielj is it available for simple forms?

**Comment by arielj** [comment] 2022-06-10 22:01
hey @snjhyrglr, the way this works is it will render whatever you put in the partial for the nested fields, I haven't tried specifically with simple form but I see no reason for that to not work since the once rails processes the partial it's just html that gets added as a data attribute

**Comment by snjhyrglr** [comment] 2022-06-13 00:18
@arielj  thanks. already found out how to use it in simple forms.

**Comment by lenilsonjr** [comment] 2022-07-13 20:50
@arielj I faced the same issue and pulling from `main` solved it, thanks for the fix!

Also, I noticed a small JS error being generated in the console and sent a PR for it here: #61

**Comment by arielj** [comment] 2022-07-17 02:20
Released version 1.6.2 that fixes this issue in both npm and rubygems so no need to use the main branch anymore, closing.

**Closed by arielj** 2022-07-17 02:20 UTC
